version: "3.8"
services:

    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: grpcdb
        ports:
            - 5432:5432
        container_name: grpcdb
    
